#! /bin/sh

xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep '*.foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep '*.background:'| awk '{print $NF}')
	COL0=$(xrdb -query | grep '*.color0:'| awk '{print $NF}')
	COL1=$(xrdb -query | grep '*.color1:'| awk '{print $NF}')
	COL2=$(xrdb -query | grep '*.color2:'| awk '{print $NF}')
	COL3=$(xrdb -query | grep '*.color3:'| awk '{print $NF}')
	COL4=$(xrdb -query | grep '*.color4:'| awk '{print $NF}')
	COL5=$(xrdb -query | grep '*.color5:'| awk '{print $NF}')
	COL6=$(xrdb -query | grep '*.color6:'| awk '{print $NF}')
	COL7=$(xrdb -query | grep '*.color7:'| awk '{print $NF}')
}
getcolors

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
# multi monitor rules
bspc monitor HDMI-A-0 -d 1 2 3 4
bspc monitor HDMI-A-1 -d 5 6 7 8  
bspc monitor DisplayPort-1 -d 9 10 


bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config top_padding          25
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a discord desktop='^9'
bspc rule -a Brave-browser desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
xrandr --output DisplayPort-0 --off --output DisplayPort-1 --mode 1920x1080 --pos 3840x0 --rotate left --output HDMI-A-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-A-1 --mode 1920x1080 --pos 1920x0 --rotate normal --output DVI-D-0 --off
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
#~/.fehbg &
nitrogen --restore &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Clipboard
greenclip daemon

